### ISSUE TITLE
fabric 1.19 crash on server startup

### ISSUE THREAD

**Issue by ghost** [marcus8448/GamemodeOverhaul#7]
[09:51:05] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulConfig.enableGamemode()" because "io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulCommon.CONFIG" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulConfig.enableGamemode()" because "io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulCommon.CONFIG" is null
        at io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulCommon.registerCommands(GamemodeOverhaulCommon.java:44) ~[GamemodeOverhaul-fabric-2.0.1+1.19.jar:?]
        at io.github.marcus8448.gamemodeoverhaul.GamemodeOverhaulFabric.lambda$onInitialize$0(GamemodeOverhaulFabric.java:25) ~[GamemodeOverhaul-fabric-2.0.1+1.19.jar:?]
        at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.1.2+0d55f585a9-fda8d30228350d7e.jar:?]
        at net.minecraft.class_2170.handler$zck000$fabric_addCommands(class_2170.java:1048) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:84) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_6904.method_40431(class_6904.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:158) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:948) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:942) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
        ... 4 more

**Comment by marcus8448** [comment]
Should be fixed as of GamemodeOverhaul 2.0.2. Thanks for the report!
